"use strict";
// Private, fixed-scope review record. Reads source data; writes only its own report.
// The decisions below record an actual question/context and targeted visual review.
// Running this helper does not perform or renew that semantic review or read H:.
const fs=require("fs"),path=require("path"),crypto=require("crypto"),vm=require("vm"),assert=require("assert/strict");
const {parseCsv,buildIbExclusions}=require("./physics-test-exclusions");
const ROOT=path.resolve(__dirname,".."), DB="C:/CodexProjects/PaperDatabases";
const SNAP=path.join(DB,"Physics Categorisation/reference/tests/3. Assessments");
const abs=p=>path.resolve(ROOT,p), sha=p=>crypto.createHash("sha256").update(fs.readFileSync(p)).digest("hex"), digest=s=>crypto.createHash("sha256").update(s).digest("hex");
const uniq=a=>[...new Set(a)].sort(), parent=r=>r.preview+"\0"+r.question;
const inputPath=abs("dist/physics-inputs/ib-d2-recovered.json"), inputHash="04fec1db6555875d25b8585fabbb1fe8fbb28d578e32eac543df4dc3266a89ae";
const corpusPath=path.join(DB,"outputs/exports/ib_physics_archive_flat_v5.csv"), corpusHash="6034e8854097c03384922d542b244164603262b1d6b0189d7a5a0ec34c13c17c";
const ledgerPath=path.join(DB,"Physics Categorisation/returns/PACKET_006D/source_results_v4.csv"), nativePath=path.join(DB,"Physics Categorisation/viewer/ibphysics_catalogue.js");
const tests=[
  ["D/D2 HL.pdf","f6062c45fdaee598cf1c39db97d278982602dbd59d8cb9d7a4c8a62bca4e0e07",15],
  ["D/D2 SL test.pdf","3804ed36cb7bf52dbaa8f7dbe4973be1c58cc1cae5c8b21ebb95cea88f0f2f6c",10],
  ["D/d1+d2 HL test.pdf","a615514451afc2c1fe101e4bc1f877369b8c886f719037206cd4aa68a95ae6ac",18],
  ["D/D1-3 SL.docx","293047a024d0de894c15949264ce3dbced730743a310b8ebda9452bfe737fe8c",null],
  ["D/D.3 test.pdf","fc1cd63c92ba933296cb9b6b383dbcc064c70b17ce634d31558ee40c2f457f58",16],
  ["D/D.4 Test.pdf","8d038e69a3f7aaf98d0571c39e7c8c08075808f702038401e35ccb7868fcbdc6",25],
  ["C/C1-C2-C5 test 2026.pdf","56eb2be04d6342d5de8950a40bb39a06551d6b38ce6f7fafc348d0e7852a31ca",27],
  ["C/C1-C2-C5 test.pdf","d3d26021b75604b23902499796f4702e9e85b7b3299dd950eaca41517eef1604",27],
  ["A/A.1/A.1 Test 2024.pdf","4dea58263039e979388bfc7e0dfde6d161c000bfe4807e209f92947434cc8f05",22],
  ["A/A.1/A.1 Test 2025.pdf","d872cda4575e52dd6d8899f06bff10bcd4db6745eb7ab49426c00f2aac7b010d",21],
  ["A/A.1/A.1 Test 2026.pdf","c4ddebc6ad090a0ccdeb995b4fe9b8b4667b68d335b7a35f278c86d62d9ea235",21]
];
const part=id=>"ibchem_part_"+id;
const manual=[
  {source_ids:[part("798f5f5b7d177bfb")],tests:["D/D2 HL.pdf p14 Part4 Q3"],kind:"same_isolated_definition",reason:"22M HL TZ2 Q7(a) asks the meaning of electric potential at a point; the school item asks its definition. Changing outline to define does not change the isolated demand."},
  {source_ids:[part("78e5ac24b6c9e566"),part("89c4faa5168ed89e")],tests:["D/D2 HL.pdf p5 Q9(c)(i)","D/D2 SL test.pdf p9 Q9(c)(i)"],kind:"plausible_rewritten_subtask",reason:"08N E3(a)(ii) explains why plastic rubbed with cloth becomes charged using the modern atomic model. The school rod subtask requests the charging method and what causes the charge. The same friction/electron-transfer explanation answers the isolated subtask; both level copies held."},
  {source_ids:[part("60ec5737dfcbb91c"),part("4cf16cf4ded0e1b1")],tests:["D/D2 HL.pdf p13 Part4 Q1"],kind:"precautionary_diagram_variant",reason:"10M HL B4/SL B3(b)(i) and the school item both require a field-line sketch around a straight current-carrying wire. The archived eye/wire perspective and current direction differ from the school out-of-page symbol; this is held as a close task variant, not an identical diagram or answer direction."},
  {source_ids:[part("caa16d4141f06a5b")],tests:["D/D2 HL.pdf p13 Part4 Q2"],kind:"precautionary_diagram_variant",reason:"05N SL Q24 chooses a solenoid's field pattern; the school task draws that pattern with supplied current arrows. Hold the isolated pattern task even though response format and directional information differ. Independently flagged incomplete crop is not used as the assessment rationale."},
  {source_ids:[part("72b3a2cf8c16d624"),part("83c748994766fb7d"),part("74e932b19ed1f544")],tests:["D/D2 HL.pdf p15 Part4 Q6"],kind:"precautionary_graph_variant",reason:"10M HL TZ2 Q20/SL Q19 and 13N HL Q23 choose the E(r) graph for a charged conductor, including zero internal field and exterior inverse-square fall. The school task draws that graph with a normalized surface value; the 13N item supplies V(r) as additional information. Hold these graph-output variants without claiming identical complete prompts."},
  {source_ids:[part("c517dc4a84fb7de9")],tests:["D/D2 HL.pdf p4 Q9(b)"],kind:"plausible_rewritten_subtask",reason:"21N HL Q7(b)(ii) predicts charges after connecting an initially charged radius48cm sphere to an uncharged radius24cm sphere. The school question uses the same2:1 radius relation and charged-large/uncharged-small setup, asking which final charge is greater and why. The connection method differs, but the school demand is a plausible subset/rewrite. Full parent must be held."},
  {source_ids:[part("0ecda768135514ad")],tests:["D/D2 HL.pdf p7 Q10(e)"],kind:"precautionary_reciprocal_recall",reason:"25M HL TZ1 Paper1A Q30 asks which scientist demonstrated charge quantization; the school asks Millikan's experimental conclusion. This is the reciprocal form of the same isolated attribution/conclusion fact, held conservatively."},
  {source_ids:[part("52242ba98a7aa0ae"),part("607edc0e165de81b"),part("7b384cc16d28e7bb"),part("86d3ea0e935adf53")],tests:["D/D2 HL.pdf p5 Q9(c)(ii)","D/D2 SL test.pdf p9 Q9(c)(ii)"],kind:"procedure_disclosed_in_source_prompt",reason:"05N SL Q23 supplies the exact gold-leaf induction sequence requested by the school: charged rod nearby, earth, remove earth, remove rod. The 07M HL/SL and25N HL plate versions also supply that sequence for an initially uncharged conductor. Hold these procedural variants; the final charge-distribution questions themselves are different."},
  {source_ids:[part("fcdeda53591784eb")],tests:["D/D2 HL.pdf p6 Q10(b)"],kind:"precautionary_labelled_diagram_variant",reason:"18M HL TZ1 Q8(c)(i) draws and labels two equipotentials between parallel electrodes at0V/-1.2V. The school draws three labelled equipotentials in a600V Millikan gap. Numerical values, orientation and number of lines differ; hold the directly corresponding labelled-line construction precautionarily."}
];
const differentiated=[
  {source_ids:[part("f6fea8ef8b617767"),part("ca2434cfc8fc88cd"),part("b110aba9aab609d8")],tests:["D/D2 HL.pdf p3 Q7","D/D2 SL test.pdf p7 Q8","D/d1+d2 HL test.pdf p5 Q11"],reason:"Inspected candidate diagrams use unequal positive/negative electric point charges and four positions, including the17M off-axis point. School electric Q7 ranks three positions for equal opposite charges; SL Q8 compares two off-axis locations from field-line density; mixedQ11 uses two attractive gravitational masses and surface points. Signs, geometry and requested comparison differ. These are shared superposition skills, not the same task."},
  {source_ids:[part("b802cabfed30bc1a")],tests:["D/D2 HL.pdf p12 Q12(a)(i)","D/d1+d2 HL test.pdf p17 Q12(a)(i)"],reason:"Candidate22M HL TZ1 Q7 uses ideal point charges atX/Y; its graph is singular at the source points. The school graph includes finite conducting spheres and their constant internal potentials. The endpoint behaviour and demanded model differ; the common outside U-shaped segment alone is insufficient evidence of a rewrite."},
  {source_ids:[part("9c0f32b10a7b98fb")],tests:["D/D2 HL.pdf p10 Q8", "D/D2 HL.pdf p15 Part4 Q6"],reason:"08M HL TZ1 Q30 selects an entire potential-versus-radius graph. School Q8 asks a statement about internal potential only; Part4Q6 asks field strength, not potential. The full graph demand and ordinate differ; common conductor knowledge alone is not a duplicate determination."},
  {source_ids:[part("9d82b231b1ea69dd"),part("1e2c8a52d39107a3"),part("e4b3b913dd699891")],tests:["D/D2 HL.pdf pp6-7 Q10","D/D2 SL test.pdf p10 Q10"],reason:"The archive tasks respectively select an E expression for constant-speed motion, a symbolic charge expression, and compare initial motion for a second oil drop of twice the radius and charge. School tasks use a fixed numerical Millikan gap/mass/voltage to calculate charge and number of electrons. None reuses those numerical tasks or their complete response demand; sharing qE=mg is not itself a match."},
  {source_ids:[],tests:["D/d1+d2 HL test.pdf pp2-5 Q5,Q6,Q9,Q10,Q11"],reason:"Rendered image-only prompts are gravitation: elliptical perihelion acceleration, inverse-square force graph, touching steel spheres, circular-orbit field, and unequal masses. They are not blank pages. Candidate D2 comparisons use electrical charge/field tasks with different signs or demands; existing structured reservations remain in force."},
  {source_ids:[],tests:["C/C1-C2-C5 test 2026.pdf Q1","A/A.1/A.1 Test 2024.pdf Q18-Q19","A/A.1/A.1 Test 2025.pdf Q18-Q19","A/A.1/A.1 Test 2026.pdf Q18-Q19"],reason:"The authored SHM initial-phase MCQ, rock/beach-ball component accelerations and timed skydiver table were compared with all184 candidate task/context texts. The D2 point-charge oscillation task asks force direction and whether the motion is SHM, not an initial phase; the proposed D2 scope contains no equivalent projectile or skydiver task. The separately identified existing-public skydiver candidate is nevertheless held through the textual-reference reconciliation."}
];
function build(){
  const files=new Map();function bind(p,expected){p=path.resolve(p);const hash=sha(p);assert(!expected||hash===expected,"Review source changed: "+p);files.set(p,{path:p,sha256:hash});return p;}
  const read=(p,expected)=>JSON.parse(fs.readFileSync(bind(p,expected),"utf8"));
  const input=read(inputPath,inputHash);bind(corpusPath,corpusHash);const corpus=parseCsv(fs.readFileSync(corpusPath,"utf8")), byId=new Map(corpus.map(r=>[r.part_id,r]));
  const candidates=uniq(input.report.candidate_source_ids);assert.equal(candidates.length,184);assert.equal(input.report.new_candidate_source_ids.length,82);assert(candidates.every(id=>byId.has(id)));
  const ledger=parseCsv(fs.readFileSync(bind(ledgerPath),"utf8"));const box={window:{}};vm.runInNewContext(fs.readFileSync(bind(nativePath),"utf8"),box);
  const current=abs("dist/physics-audit/current-ib-tests.json"), extras=[abs("reports/ib-a5-reviewed-test-exclusions.json"),abs("reports/ib-a1-c1-reviewed-test-exclusions.json")];
  [current,...extras,abs("reports/ib-five-named-assessments-review.json"),abs("reports/ib-a1-skydiver-note-review.json"),path.join(DB,"Physics Categorisation/returns/PACKET_006D/matches.csv")].forEach(p=>bind(p));
  const saved=read(current);const reviewedTests=tests.map(([relative,hash,pages])=>{bind(path.join(SNAP,relative),hash);assert(saved.source_files.some(f=>f.relative_path===relative&&f.sha256===hash));return {relative_path:relative,sha256:hash,pages,observed_on:"2026-09-12",observed_location:relative==="C/C1-C2-C5 test 2026.pdf"?"local supplied PDF":"shared-drive read-only hash observation",matches_saved_snapshot:true};});
  const base=buildIbExclusions({paperdbRoot:DB,questions:box.window.IBPHYS_QUESTIONS,extraExclusionsPath:current,extraExclusionsPaths:extras});
  base.report.sourceFiles.forEach(f=>bind(path.isAbsolute(f.path)?f.path:path.join(DB,f.path),f.sha256));
  const relativeSet=new Set(tests.map(x=>x[0]));const notes=ledger.filter(r=>r.source_kind==="test"&&[...relativeSet].some(p=>r.source_file.replace(/\\/g,"/").endsWith("/"+p)));
  const references=[], unresolvedReferences=[];for(const n of notes){const re=/(20\d\d)\s+(May|Nov)(?:\s+(TZ[0123]))?\s+P(1A|1B|[123])\s+(HL|SL)\s+Q([A-Z]?\d+)\b/g;for(const m of n.notes.matchAll(re)){
    const rows=corpus.filter(r=>r.year===m[1]&&r.session===m[2]&&r.paper===m[4]&&r.level===m[5]&&r.question===m[6]&&(!m[3]||r.time_zone===m[3]));
    const evidence={test_source_part_id:n.source_part_id,test_source_file:n.source_file,test_page:n.source_page,test_question:n.source_q_label,note_sha256:digest(n.notes),reference:m[0],proposed_verdict:n.proposed_verdict,resolved_source_ids:uniq(rows.map(r=>r.part_id))};
    if(!rows.length)unresolvedReferences.push(evidence);else references.push(evidence);
  }}
  // All attributable alternatives remain holds, including weak/bespoke retrievals.
  // This supplement reconciles named sittings; it never removes an existing hold.
  const addedReferences=uniq(references.flatMap(r=>r.resolved_source_ids).filter(id=>!base.blockedSourceIds.has(id)));
  const seeds=uniq([...manual.flatMap(r=>r.source_ids),...addedReferences]);assert(seeds.every(id=>byId.has(id)));
  const byParent=new Map(), byGroup=new Map(), dup=new Map();const add=(m,k,id)=>{if(!k)return;if(!m.has(k))m.set(k,new Set());m.get(k).add(id);};
  for(const r of corpus){add(byParent,parent(r),r.part_id);add(byGroup,r.cross_level_group_id,r.part_id);if(r.duplicate_of){add(dup,r.part_id,r.duplicate_of);add(dup,r.duplicate_of,r.part_id);}}
  const held=new Set(),pending=[];const put=id=>{assert(byId.has(id),"Unknown closure ID");if(!held.has(id)){held.add(id);pending.push(id);}};seeds.forEach(put);
  for(let i=0;i<pending.length;i++){const r=byId.get(pending[i]);for(const id of [...byParent.get(parent(r)),...(byGroup.get(r.cross_level_group_id)||[]),...(dup.get(r.part_id)||[])])put(id);}
  const heldPages=new Set();for(const id of held){const r=byId.get(id);for(const p of r.page_render_paths.split(";")){if(/^pages\/question_/.test(p))heldPages.add(r.preview+"/"+Number((/_p(\d+)(?:_|\.)/.exec(p)||[])[1]));}}
  const owners=new Map(input.questions.flatMap(q=>q.parts.map(p=>[p.source_part_id,q])));
  const candidateReview=candidates.map(id=>{const r=byId.get(id),q=owners.get(id);const pageHold=[...(q.pages||[]),...(q.crops||[]),...q.parts.flatMap(p=>p.crops||[])].some(p=>heldPages.has(q.preview+"/"+Number((/_p(\d+)(?:_|\.)/.exec(p)||[])[1])));
    return {source_part_id:id,parent_id:q.id,source_reference:[r.year,r.session,r.time_zone,r.paper,r.level,r.question,r.part_label].join(" "),question_text_sha256:digest(r.question_text||""),context_text_sha256:digest([r.shared_stem,r.parent_context].join("\n")),review_complete:true,disposition:held.has(id)?"hold_full_parent_twin_duplicate":pageHold?"hold_shared_question_context_page":"no_additional_scoped_assessment_hold",manual_review_groups:manual.map((m,i)=>m.source_ids.includes(id)?i+1:null).filter(Boolean)};});
  input.report.asset_manifest.forEach(f=>bind(f.path,f.sha256));
  // Bind the actual rendered pages viewed, as well as their original PDFs.
  for(const folder of [abs("tmp/pdfs/d2-assessment-review"),abs("tmp/pdfs/named-assessment-review")])for(const file of fs.readdirSync(folder))if(/\.png$/i.test(file))bind(path.join(folder,file));
  const output={schema_version:1,topic:"D.2",review_complete:true,reviewed_on:"2026-09-12",reviewed_candidate_source_ids:candidates,reviewed_candidate_file:inputPath,reviewed_candidate_sha256:inputHash,corpus_sha256:corpusHash,
    blocked_source_ids:seeds,read_failures:[],unresolved_relevant_items:[],reviewed_tests:reviewedTests,manual_reservations:manual,reviewed_differences:differentiated,
    attributable_note_references:references,unresolved_note_references:unresolvedReferences,candidate_review:candidateReview,
    counts:{candidate_parts:184,candidate_parents:input.questions.length,new_recovered_parts:82,manual_seed_parts:uniq(manual.flatMap(r=>r.source_ids)).length,attributable_references:references.length,note_reference_new_ids:addedReferences.length,additional_seed_parts:seeds.length,full_corpus_closed_parts:held.size,candidate_parent_or_twin_holds:candidateReview.filter(r=>r.disposition==="hold_full_parent_twin_duplicate").length,candidate_shared_page_holds:candidateReview.filter(r=>r.disposition==="hold_shared_question_context_page").length,candidate_without_additional_scoped_hold:candidateReview.filter(r=>r.disposition==="no_additional_scoped_assessment_hold").length},
    closed_source_ids:[...held].sort(),source_files:[...files.values()].sort((a,b)=>a.path.localeCompare(b.path)),builder:{path:__filename,sha256:sha(__filename)},
    method:["Read all184 exact candidate question/shared-stem/parent-context texts and compared the requested operations with the six D-related current assessments plus the five named A1/C PDFs, including authored tasks.","Inspected every page of the D2 HL and SL PDFs, and the mixed D1/D2 image-only pages2-5. Inspected the targeted archive charging, field sketch, graph, charge-sharing and equipotential crops. Earlier complete A1/C review plus the named-version visual comparison is hash-bound as evidence.","Retained all existing matches, proposed alternatives, sibling/twin/duplicate and question-page holds. Corrected textual historical citations are added conservatively; weak proposals are not relabelled confirmed matches.","This completed semantic review has hold outcomes. It does not assert that184parts may be published. The separate release helper must reapply full archive/page/rectangle exclusions, source-scope and image-quality holds before projecting retained records."],
    limitations:["Fixed scope and fixed source bytes only; no certification of unreviewed future recovered parts.","Other125-file assessment reservations remain additive. The global test-note reference audit must also be applied; this eleven-file citation reconciliation does not claim to scan all review notes.","No crop-quality or current-syllabus certification is granted by this assessment report. Visual/source gates remain mandatory.","Private assessment details must not appear in public data or UI."]};
  assert.equal(unresolvedReferences.length,0,"Unresolved attributable historical references require review before completing this report");return output;
}
if(require.main===module){const result=build();fs.writeFileSync(abs("reports/ib-d2-reviewed-test-exclusions.json"),JSON.stringify(result,null,2)+"\n");console.log(JSON.stringify(result.counts));}
module.exports={build};
