/* Generate human-readable labels for AA spine codes from the Maths seat's
   syllabus_spine.csv ("no way people are going to know what SL1.2 is").
   Output: example/ibmaths_spine_labels.js -> window.IBMATHS_SPINE_LABELS
   { "SL1.2": "Arithmetic sequences and series", "SL1.2.3": "...", ... }
   Short labels: the content line's first clause, trimmed. Interim until the
   seat ships canonical prose in the catalogue META. Claude, 2026-07-29. */
"use strict";
const fs = require("fs");
const path = require("path");
const PROJECT_ROOT = path.resolve(__dirname, "..");
const SPINE = process.env.IBMATHS_SPINE_CSV ||
  "C:\\CodexProjects\\PaperDatabases\\Maths Categorisation\\syllabus_spine.csv";
const OUT = path.join(PROJECT_ROOT, "example", "ibmaths_spine_labels.js");

function parseCSV(text) {
  const rows = [];
  let row = [], field = "", inQ = false;
  for (let i = 0; i < text.length; i++) {
    const c = text[i];
    if (inQ) {
      if (c === '"') { if (text[i + 1] === '"') { field += '"'; i++; } else inQ = false; }
      else field += c;
    } else {
      if (c === '"') inQ = true;
      else if (c === ",") { row.push(field); field = ""; }
      else if (c === "\n") { row.push(field.replace(/\r$/, "")); field = ""; rows.push(row); row = []; }
      else field += c;
    }
  }
  if (field.length || row.length) { row.push(field.replace(/\r$/, "")); rows.push(row); }
  return rows;
}
function shorten(content) {
  let s = String(content || "").trim().replace(/\s+/g, " ");
  /* first sentence/clause, then trim to ~60 chars on a word boundary */
  const cut = s.split(/(?<=[a-z\)])\.\s/)[0].split(";")[0].split(":")[0];
  s = cut.trim();
  if (s.length > 60) {
    s = s.slice(0, 60);
    const sp = s.lastIndexOf(" ");
    if (sp > 30) s = s.slice(0, sp);
    s += "…";
  }
  return s;
}
const rows = parseCSV(fs.readFileSync(SPINE, "utf8"));
const header = rows[0].map((h) => h.replace(/^\uFEFF/, "").trim());
const idx = {}; header.forEach((h, i) => { idx[h] = i; });
const labels = {};
const partSeen = {};
rows.slice(1).forEach((r) => {
  const code = r[idx.code];
  if (!code) return;
  const tp = r[idx.topic_part];
  const content = r[idx.content];
  labels[code] = shorten(content);
  /* topic_part label = the first item's content stem (best available) */
  if (tp && !partSeen[tp]) { partSeen[tp] = true; labels[tp] = labels[tp] || shorten(content); }
});
fs.writeFileSync(OUT,
  "/* GENERATED by tools/build_ibmaths_spine_labels.js from the Maths seat's\n" +
  "   syllabus_spine.csv — do not hand-edit. Interim until canonical prose\n" +
  "   ships in the catalogue META. */\n" +
  "window.IBMATHS_SPINE_LABELS = " + JSON.stringify(labels) + ";\n", "utf8");
console.log("spine labels: " + Object.keys(labels).length + " codes -> " + OUT);
