"use strict";
// Read-only diagnosis of the D2 clearance against current sources.
//
// Why this exists: `dist/physics-inputs/ib-d2.json` was regenerated by the preview
// refresh, and the D2 clearance fingerprints it. Exactly one of the 79 repo-side
// fingerprints in that clearance is now stale, and the clearance's own driving input,
// `ib-d2-recovered.json`, still matches. That points at provenance noise rather than a
// change in what the release serves, but it has to be proved, not assumed.
//
// So this rebuilds the D2 clearance in memory from current sources and compares it to
// the stored one field by field. It writes nothing.
//
//   reviewed_source_part_ids, reviewed_parent_ids, counts, assets   what the release serves
//   fingerprints                                                    the provenance record
//
// If only `fingerprints` moved, and only the ib-d2.json entry inside it, the regenerated
// clearance is safe to promote. Anything else is a real change and needs a human.
//
// Usage: node tools/diagnose_d2_clearance.js

const fs = require("fs"), path = require("path");
const { prepareRelease, clearancePath } = require("./ib-d2-release");

const FIELDS = ["reviewed_source_part_ids", "reviewed_parent_ids", "counts", "assets", "fingerprints"];

function fingerprintDelta(before, after) {
  const was = new Map((before || []).map(f => [path.resolve(f.path), f.sha256]));
  const now = new Map((after || []).map(f => [path.resolve(f.path), f.sha256]));
  const moved = [];
  for (const [file, sha] of now) {
    if (!was.has(file)) moved.push({ kind: "added", file });
    else if (was.get(file) !== sha) moved.push({ kind: "changed", file, from: was.get(file), to: sha });
  }
  for (const file of was.keys()) if (!now.has(file)) moved.push({ kind: "removed", file });
  return moved;
}

let rebuilt;
try {
  rebuilt = prepareRelease();
} catch (error) {
  console.log("The D2 rebuild REFUSED before it could be compared:");
  console.log("  " + error.message);
  console.log("");
  console.log("That refusal is itself the answer: a source it checks against a recorded");
  console.log("sha has moved. Nothing has been written.");
  process.exit(1);
}

const stored = JSON.parse(fs.readFileSync(clearancePath, "utf8"));
const differing = FIELDS.filter(field =>
  JSON.stringify(stored[field]) !== JSON.stringify(rebuilt.clearance[field]));

console.log("Stored clearance: " + clearancePath);
console.log("");
for (const field of FIELDS) {
  const same = differing.indexOf(field) < 0;
  const size = value => Array.isArray(value) ? value.length + " entries"
    : value && typeof value === "object" ? Object.keys(value).length + " keys" : String(value);
  console.log("  " + (same ? "same     " : "DIFFERENT") + "  " + field +
    "  (" + size(stored[field]) + " stored, " + size(rebuilt.clearance[field]) + " rebuilt)");
}
console.log("");

const contentMoved = differing.filter(field => field !== "fingerprints");
if (contentMoved.length) {
  console.log("STOP. The release content itself has moved: " + contentMoved.join(", ") + ".");
  console.log("This is not provenance noise. Nothing has been written.");
  process.exit(1);
}

if (differing.indexOf("fingerprints") < 0) {
  console.log("Nothing moved at all, including the fingerprints.");
  process.exit(0);
}

const moved = fingerprintDelta(stored.fingerprints, rebuilt.clearance.fingerprints);
console.log("Fingerprints that moved: " + moved.length);
for (const entry of moved) {
  console.log("  " + entry.kind.toUpperCase() + " " + entry.file);
  if (entry.kind === "changed") console.log("    " + entry.from.slice(0, 16) + " -> " + entry.to.slice(0, 16));
}
console.log("");

const onlySuspect = moved.length === 1 && moved[0].kind === "changed" &&
  path.basename(moved[0].file) === "ib-d2.json";
if (onlySuspect) {
  console.log("Everything the release serves is identical. The only thing that moved is the");
  console.log("recorded sha of ib-d2.json, which the preview refresh rewrote.");
  console.log("The regenerated clearance is safe to promote.");
  process.exit(0);
}
console.log("More than the expected file moved. A human looks before anything is promoted.");
process.exit(1);
